<a href="https://colab.research.google.com/github/Arimoro2020/food-sales-predictions./blob/main/2021_W5_Renewables_Overtake_Fossil_Fuels_in_Europe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Recreating Ember's Renewables overtake fossil fuels
% share of electricity production in EU-27 interactive chart

In [1]:
# mount drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
#import libraries
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np



In [3]:
#load data
filename = '/content/drive/MyDrive/PTDataScience/Python_for_Data_Visualization/Data-file-Europe-Power-Sector-2020.xlsx'
fossil_data_df = pd.read_excel(filename)
fossil_data_df.head()

Year     Area  ... Change on last year (%)  Change on last year (TWh)
0  2000  Austria  ...                     NaN                        NaN
1  2000  Austria  ...                     NaN                        NaN
2  2000  Austria  ...                     NaN                        NaN
3  2000  Austria  ...                     NaN                        NaN
4  2000  Austria  ...                     NaN                        NaN

[5 rows x 7 columns]

In [4]:
#check for miissing data
fossil_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10710 entries, 0 to 10709
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Year                       10710 non-null  int64  
 1   Area                       10710 non-null  object 
 2   Variable                   10710 non-null  object 
 3   Generation (TWh)           10710 non-null  float64
 4   Share of production (%)    8820 non-null   float64
 5   Change on last year (%)    8611 non-null   float64
 6   Change on last year (TWh)  10200 non-null  float64
dtypes: float64(4), int64(1), object(2)
memory usage: 585.8+ KB


In [5]:
# Check for countries in EU-27. should be 27 countries
fossil_data_df['Area'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Estonia', 'EU-27', 'EU27+1',
       'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Ireland',
       'Italy', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta',
       'Netherlands', 'Poland', 'Portugal', 'Romania', 'Slovakia',
       'Slovenia', 'Spain', 'Sweden', 'United Kingdom'], dtype=object)

In [6]:
# Drop irrelevant data: UK
uk_filter = fossil_data_df[fossil_data_df['Area'] == 'United Kingdom']
uk = np.array(uk_filter.index)
fossil_data_df.drop(uk, axis=0, inplace=True)
fossil_data_df['Area'].unique()


array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Estonia', 'EU-27', 'EU27+1',
       'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Ireland',
       'Italy', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta',
       'Netherlands', 'Poland', 'Portugal', 'Romania', 'Slovakia',
       'Slovenia', 'Spain', 'Sweden'], dtype=object)

In [7]:
# Drop irrelevant data: 'EU27+1'
plusone_filter = fossil_data_df[fossil_data_df['Area'] == 'EU27+1']
plusone = np.array(plusone_filter.index)
fossil_data_df.drop(plusone, axis=0, inplace=True)
fossil_data_df['Area'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Estonia', 'EU-27', 'Finland',
       'France', 'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy',
       'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Netherlands',
       'Poland', 'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain',
       'Sweden'], dtype=object)

In [8]:
# Check for missing data again
fossil_data_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9996 entries, 0 to 10692
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Year                       9996 non-null   int64  
 1   Area                       9996 non-null   object 
 2   Variable                   9996 non-null   object 
 3   Generation (TWh)           9996 non-null   float64
 4   Share of production (%)    8232 non-null   float64
 5   Change on last year (%)    7951 non-null   float64
 6   Change on last year (TWh)  9520 non-null   float64
dtypes: float64(4), int64(1), object(2)
memory usage: 624.8+ KB


In [9]:
# check where 'share of production (%)' have missing values
shareisna = fossil_data_df[fossil_data_df['Share of production (%)'].isna()]
shareisna['Variable'].unique()

array(['Production', 'Net imports', 'Demand'], dtype=object)

In [10]:
# create dataframe with 'EU-27' as Area
eu_df =fossil_data_df[fossil_data_df['Area'] == 'EU-27']
eu_df.tail(20)

Year   Area  ... Change on last year (%)  Change on last year (TWh)
9840   2019  EU-27  ...               -1.216522                 -35.487355
9841   2019  EU-27  ...              -79.628032                  -7.071574
9842   2019  EU-27  ...               -1.454510                 -42.558930
10336  2020  EU-27  ...              -10.430269                -118.812212
10337  2020  EU-27  ...              -19.879352                 -90.496305
10338  2020  EU-27  ...              -21.980067                 -46.361217
10339  2020  EU-27  ...              -18.065663                 -44.135087
10340  2020  EU-27  ...               -3.776770                 -21.375160
10341  2020  EU-27  ...               -5.886074                  -6.940747
10342  2020  EU-27  ...              -10.487438                 -80.267860
10343  2020  EU-27  ...                7.899158                  77.186458
10344  2020  EU-27  ...                8.455735                  27.409875
10345  2020  EU-27  ...               10.458052                  51.142004
10346  2020  EU-27  ...                8.977566                  32.658906
10347  2020  EU-27  ...               14.758515                  18.483098
10348  2020  EU-27  ...               -0.846558                  -1.326853
10349  2020  EU-27  ...               -0.533060                  -0.038569
10350  2020  EU-27  ...               -4.230024                -121.893614
10351  2020  EU-27  ...              930.835844                  16.840548
10352  2020  EU-27  ...               -3.643326                -105.053066

[20 rows x 7 columns]

In [11]:
# Check for unique variables
fossil_data_df['Variable'].unique()

array(['Fossil', 'Coal', 'Hard Coal', 'Lignite', 'Gas', 'Other fossil',
       'Nuclear', 'Renewables', 'Hydro', 'Wind and solar', 'Wind',
       'Solar', 'Bioenergy', 'Other renewables', 'Production',
       'Net imports', 'Demand'], dtype=object)

In [12]:
# Generation values for renewables in (TWh)
filter1 = eu_df['Variable'] == 'Hydro'
filter2 = eu_df['Variable'] == 'Wind and solar'
filter3 = eu_df['Variable'] == 'Wind'
filter4 = eu_df['Variable'] == 'Solar'
filter5 = eu_df['Variable'] == 'Other renewables'
filter6 = eu_df['Variable'] == 'Renewables'
filter7 = eu_df['Variable'] == 'Bioenergy'
renewable = eu_df[filter1 | filter3 | filter4 | filter5 | filter7]
generation = renewable.groupby('Year')['Generation (TWh)'].sum()
a = generation.values
a

array([ 410.942705  ,  439.079484  ,  393.133697  ,  398.496846  ,
        441.241018  ,  444.891626  ,  468.560922  ,  497.701896  ,
        541.945561  ,  572.384721  ,  653.92726   ,  645.577833  ,
        728.439665  ,  806.91877   ,  837.650952  ,  856.50752   ,
        871.828567  ,  875.614082  ,  942.60841   ,  977.14797849,
       1054.33443646])

In [13]:
# Years are from 2000 to 2020
x = generation.index
x


Int64Index([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
            2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020],
           dtype='int64', name='Year')

In [14]:
# Production Values per year
production_filter = eu_df['Variable'] == 'Production'
production = eu_df[production_filter]
production_val = production.groupby('Year')['Generation (TWh)'].mean()
b = production_val.values
b

array([2629.21708   , 2705.852275  , 2723.66442   , 2805.392041  ,
       2873.59166   , 2888.546996  , 2940.826295  , 2955.538945  ,
       2968.996899  , 2817.216775  , 2954.380045  , 2914.034199  ,
       2908.963177  , 2889.104488  , 2829.879658  , 2876.87391   ,
       2898.291276  , 2929.632221  , 2917.116593  , 2881.62923771,
       2759.73562341])

In [15]:
# Share % of renewables per year
share_renewable = []
for i in range(len(a)):
  share = (a[i]/b[i]) * 100
  share_renewable.append(share)

share_renewable = np.round(share_renewable, 1) 
share_renewable 
    

array([15.6, 16.2, 14.4, 14.2, 15.4, 15.4, 15.9, 16.8, 18.3, 20.3, 22.1,
       22.2, 25. , 27.9, 29.6, 29.8, 30.1, 29.9, 32.3, 33.9, 38.2])

In [16]:
# Generation values in (TWh) of Fossil feuls per year
filter8 = eu_df['Variable'] == 'Fossil'
generation_fossil = eu_df[filter8]
generation_fossil_val = generation_fossil.groupby('Year')['Generation (TWh)'].mean()
c = generation_fossil_val.values
c




array([1358.350375  , 1377.885791  , 1428.224723  , 1499.681195  ,
       1503.877642  , 1527.62937   , 1557.708373  , 1585.622049  ,
       1542.017338  , 1419.952054  , 1445.938785  , 1430.658603  ,
       1368.522495  , 1275.953047  , 1179.707697  , 1233.677582  ,
       1258.538227  , 1294.659496  , 1212.570135  , 1139.10973894,
       1020.29752707])

In [17]:
# Share % of Fossil fuel Production per year
share_fossil = []
for i in range(len(c)):
  share = (c[i]/b[i]) * 100
  share_fossil.append(share)

share_fossil = np.round(share_fossil, 1)
share_fossil

array([51.7, 50.9, 52.4, 53.5, 52.3, 52.9, 53. , 53.6, 51.9, 50.4, 48.9,
       49.1, 47. , 44.2, 41.7, 42.9, 43.4, 44.2, 41.6, 39.5, 37. ])

In [18]:
# Generation values of Wind & Solar per year in (TWh)
wind_solar = eu_df[filter2]
ws = wind_solar.groupby('Year')['Generation (TWh)'].sum()
d = ws.values
d

array([ 21.517209  ,  25.946982  ,  35.284752  ,  43.822649  ,
        58.341223  ,  69.69705   ,  81.25668   , 103.700171  ,
       120.667518  , 138.794579  , 163.090205  , 212.678423  ,
       257.577632  , 293.531771  , 316.572577  , 364.012818  ,
       367.945191  , 420.241142  , 435.565941  , 489.02037361,
       540.16237762])

In [19]:
# Share % of Wind & Solar of Production per year
share_ws = []
for i in range(len(d)):
  share = (d[i]/b[i]) * 100
  share_ws.append(share)

share_ws = np.round(share_ws, 1) 
share_ws

array([ 0.8,  1. ,  1.3,  1.6,  2. ,  2.4,  2.8,  3.5,  4.1,  4.9,  5.5,
        7.3,  8.9, 10.2, 11.2, 12.7, 12.7, 14.3, 14.9, 17. , 19.6])

In [20]:
# generation values for Coal per year in (TWh)
filter9 = eu_df['Variable'] == 'Coal'
coal_filter = eu_df[filter9]
cl = coal_filter.groupby('Year')['Generation (TWh)'].sum()
e = cl.values
e

array([795.053     , 792.372     , 807.352     , 849.114     ,
       835.444     , 808.939221  , 816.229869  , 828.794459  ,
       757.034054  , 703.612826  , 701.231144  , 725.265759  ,
       743.577179  , 728.913822  , 692.742333  , 704.991847  ,
       659.126602  , 638.888604  , 595.654605  , 455.22763515,
       364.73133055])

In [21]:
# share % of Coal in Production per year
share_cl = []
for i in range(len(e)):
  share = (e[i]/b[i]) * 100
  share_cl.append(share)

share_cl = np.round(share_cl, 1)
share_cl

array([30.2, 29.3, 29.6, 30.3, 29.1, 28. , 27.8, 28. , 25.5, 25. , 23.7,
       24.9, 25.6, 25.2, 24.5, 24.5, 22.7, 21.8, 20.4, 15.8, 13.2])

In [22]:
import plotly.graph_objects as go
import numpy as np

title = "Renewables overtake fossil fuels\n"\
        "% share of electricity production in EU-27"
        
labels = ['Fossil fuel', 'Renewable', 'Coal', 'Wind and Solar']
colors = ['rgb(42, 46, 41)', 'rgb(34, 156, 16)', 'rgb(132, 135, 131)', 'rgb(38, 240, 7)']
mode_style = ['lines+markers', 'lines+markers', 'lines+markers', 'lines+markers']
mode_size = [8, 8, 12, 8]
line_size = [2.5, 2.5, 2.5, 2.5]

x_data = [x, x, x, x]

y_data = [share_fossil, share_renewable, share_cl, share_ws]


fig = go.Figure()

for i in range(0, 4):
    fig.add_trace(go.Scatter(x=x_data[i], y=y_data[i], mode=mode_style[i],
        name=labels[i],
        line=dict(color=colors[i], width=line_size[i]),
        connectgaps=True,
    ))

    # endpoints
    fig.add_trace(go.Scatter(
        x=[x_data[i][0], x_data[i][-1]],
        y=[y_data[i][0], y_data[i][-1]],
        mode='markers',
        marker=dict(color=colors[i], size=8)
    ))
fig.update_layout(
    xaxis=dict(
        showline=True,
        showgrid=False,
        showticklabels=True,
        linecolor='rgb(204, 204, 204)',
        linewidth=2,
        ticks='outside',
        tickfont=dict(
            family='Arial',
            size=12,
            color='rgb(82, 82, 82)',
        ),
    ),
    width=1000,
    height=700,
    yaxis=dict(
        showgrid=True,
        zeroline=True,
        showline=False,
        showticklabels=True,
    ),
    autosize=False,
    margin=dict(
        autoexpand=False,
        l=120,
        r=120,
        t=120,
    ),
    showlegend=False,
    plot_bgcolor='rgb(243, 245, 242)'
)
    
fig.update_xaxes(range=['2010', '2020'], nticks=11)
fig.update_yaxes(gridcolor='rgb(169, 173, 168)')
annotations = []

# Adding labels
for y_trace, label, color in zip(y_data, labels, colors):
    # labeling the left_side of the plot
    annotations.append(dict(xref='paper', x=0, y=y_trace[10],
                                  xanchor='right', yanchor='middle',
                                  text=' {}%'.format(y_trace[10]),
                                  font=dict(family='Arial',
                                            size=11),
                                  showarrow=False))
    # labeling the right_side of the plot
    annotations.append(dict(xref='paper', x=1, y=y_trace[20],
                                  xanchor='left', yanchor='middle',
                                  text=label.format(y_trace[20]),
                                  font=dict(family='Arial',
                                            size=15),
                                  showarrow=False))
# Title
annotations.append(dict(xref='paper', yref='paper', x=0.0, y=0.99,
                              xanchor='left', yanchor='top',
                              text="Renewables overtake fossil fuels",
                              font=dict(family='Arial',
                                        size=24,
                                        color='rgb(42, 46, 41)'),
                              showarrow=False))
annotations.append(dict(xref='paper', yref='paper', x=0.0, y=0.94,
                              xanchor='left', yanchor='top',
                              text="% share of electricity production in EU-27",
                              font=dict(family='Arial',
                                        size=16,
                                        color='rgb(42, 46, 41)'),
                              showarrow=False))
# Source
annotations.append(dict(xref='paper', yref='paper', x=0.43, y=0.05,
                              xanchor='center', yanchor='top',
                              text="\"Europe's Power Sector in 2020\"" + ", published by Ember and Agora Energiewende on 25th January 2021.",
                              font=dict(family='Arial',
                                        size=14,
                                       color='rgb(150,150,150)'),
                              showarrow=False))
fig.update_layout(annotations=annotations)


fig.show()
